server:
  port: 8080
  error:
    include-stacktrace: ALWAYS
spring:
  data:
    mongodb:
      authentication-database: admin
      username: admin
      password: 123
      database: test_db
      port: 27017
      host: localhost