server:
  port: 8080
  error:
    include-stacktrace: NEVER

spring:
  data:
    mongodb:
      uri: ${MONGO_DB}
      #auto-index-creation: true   # Automatically create indexes
      #uri: mongodb://admin:123@localhost:27017/miniEcommerceDB?authSource=admin

github:
  api:
    url:${GITHUB_URL}
  access:
    token:${GITHUB_ACCESS_TOKEN}

projeto:
  jwtExpirationMs: 900000
  jwtSecret: bxOksa8BHgdAhR80Y3pEYvS5M+MnF2sheFDqprkTqQ4odqoszJLW1ikw64/nT/dTvlgrcBTq7HfK1B9Gai2h5A==